name: AI News Pipeline

on:
  schedule:
    - cron: "0 * * * *" # Run every hour at minute 0
  workflow_dispatch: # Allow manual trigger

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pipeline
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python main.py --slack-channel "C09AUR5G62Y"

      - name: Commit last_processed.json
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add last_processed.json || true
          git diff --quiet && git diff --staged --quiet || git commit -m "Update last_processed.json [skip ci]"
          git push || true
